spring.application.name=codeguard

# Gemini
gemini.api.key=${GEMINI_API_KEY}

# GitHub App
github.app.id=${GITHUB_APP_ID}
github.private-key-path=${GITHUB_PRIVATE_KEY_PATH}
github.webhook-secret=${GITHUB_WEBHOOK_SECRET}

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/codeguard
spring.datasource.username=root
spring.datasource.password=${MYSQL_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true